"""Refactor V2: Factory Automation Schema

Revision ID: ffa0b6b77e92
Revises: 
Create Date: 2026-01-07 20:07:11.466250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ffa0b6b77e92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_hex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filaments_collection_id'), 'filaments', ['collection_id'], unique=True)
    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('printer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', postgresql.ENUM(name='jobstatus', create_type=False), nullable=False),
    sa.Column('required_material', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_color_hex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('used_ams_slot', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.serial'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_requirements')
    op.drop_table('ams_slots')
    op.drop_table('filament_profiles')
    op.drop_index(op.f('ix_jobs_priority'), table_name='jobs')
    op.drop_table('jobs')
    op.alter_column('print_files', 'upload_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('printers', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='A1'))
    op.add_column('printers', sa.Column('current_state', postgresql.ENUM(name='printerstate', create_type=False), nullable=False, server_default='IDLE'))
    op.add_column('printers', sa.Column('ams_config', sa.JSON(), nullable=True))
    op.add_column('printers', sa.Column('supports_auto_eject', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('printers', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('printers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('printers', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('printers', 'access_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('printers', 'current_temp_bed')
    op.drop_column('printers', 'last_error_code')
    op.drop_column('printers', 'type')
    op.drop_column('printers', 'last_error_description')
    op.drop_column('printers', 'calibration_interval')
    op.drop_column('printers', 'remaining_time')
    op.drop_column('printers', 'current_status')
    op.drop_column('printers', 'jobs_since_calibration')
    op.drop_column('printers', 'current_progress')
    op.drop_column('printers', 'is_plate_cleared')
    op.drop_column('printers', 'hardware_model')
    op.drop_column('printers', 'current_job_id')
    op.drop_column('printers', 'thermal_release_temp')
    op.drop_column('printers', 'can_auto_eject')
    op.drop_column('printers', 'last_error_time')
    op.drop_column('printers', 'clearing_strategy')
    op.drop_column('printers', 'ams_data')
    op.drop_column('printers', 'current_temp_nozzle')
    op.alter_column('product_skus', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Unnamed SKU'::character varying"))
    op.alter_column('product_skus', 'is_catalog_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'is_catalog_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'is_continuous_printing',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'is_continuous_printing',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'is_catalog_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product_skus', 'is_catalog_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('product_skus', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Unnamed SKU'::character varying"))
    op.add_column('printers', sa.Column('current_temp_nozzle', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('ams_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('printers', sa.Column('clearing_strategy', postgresql.ENUM('MANUAL', 'A1_INERTIAL_FLING', 'X1_MECHANICAL_SWEEP', 'A1_GANTRY_SWEEP', 'A1_TOOLHEAD_PUSH', name='clearingstrategyenum'), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('last_error_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('printers', sa.Column('can_auto_eject', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('thermal_release_temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('current_job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('printers', sa.Column('hardware_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('printers', sa.Column('is_plate_cleared', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('current_progress', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('jobs_since_calibration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('current_status', postgresql.ENUM('IDLE', 'PRINTING', 'OFFLINE', 'AWAITING_CLEARANCE', 'COOLDOWN', 'CLEARING_BED', 'ERROR', 'PAUSED', name='printerstatusenum'), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('remaining_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('calibration_interval', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('last_error_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('printers', sa.Column('type', postgresql.ENUM('P1S', 'A1', 'X1C', name='printertypeenum'), autoincrement=False, nullable=False))
    op.add_column('printers', sa.Column('last_error_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('printers', sa.Column('current_temp_bed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('printers', 'access_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('printers', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('printers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('printers', 'last_seen')
    op.drop_column('printers', 'supports_auto_eject')
    op.drop_column('printers', 'ams_config')
    op.drop_column('printers', 'current_state')
    op.drop_column('printers', 'model')
    op.alter_column('print_files', 'upload_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_printer_serial', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gcode_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'UPLOADING', 'PRINTING', 'FINISHED', 'FAILED', name='jobstatusenum'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filament_requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('job_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_printer_serial'], ['printers.serial'], name=op.f('jobs_assigned_printer_serial_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('jobs_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('ix_jobs_priority'), 'jobs', ['priority'], unique=False)
    op.create_table('filament_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('material', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color_hex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('density', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('spool_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('color_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='filament_profiles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ams_slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('printer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ams_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color_hex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('material', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('remaining_percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.serial'], name=op.f('ams_slots_printer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ams_slots_pkey')),
    sa.UniqueConstraint('printer_id', 'ams_index', 'slot_index', name=op.f('unique_ams_slot'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('product_requirements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_sku_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filament_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['filament_profile_id'], ['filament_profiles.id'], name=op.f('product_requirements_filament_profile_id_fkey')),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], name=op.f('product_requirements_product_sku_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_requirements_pkey'))
    )
    op.drop_table('print_jobs')
    op.drop_index(op.f('ix_filaments_collection_id'), table_name='filaments')
    op.drop_table('filaments')
    # ### end Alembic commands ###
